
GET https://fitapi.rudyah.com/users

###

POST https://fitapi.rudyah.com/register
Content-Type: application/x-www-form-urlencoded

username=frankie
&password=bvtca3
&passwordConfirm=bvtca3
&gender=male
&height=65
&birthDate=01/01/1990

###

POST https://fitapi.rudyah.com/login HTTP/2.0
Content-Type: application/x-www-form-urlencoded

username=rudyah
&password=Imogen123

###
@userId=60b32a1eaa1c55833eff415d
@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYjMyYTFlYWExYzU1ODMzZWZmNDE1ZCIsImlhdCI6MTY0MzQ3NzUzMiwiZXhwIjoxNjQzNTYzOTMyfQ.tLsSlJjVT5N8nw2MSOsO35A2cI-84KAG5tuK_nIg2AM


###
GET https://fitapi.rudyah.com/users/{{userId}}/settings
Authorization: Bearer {{authToken}}


# measurements

###
GET https://fitapi.rudyah.com/users/{{userId}}/measurements
Authorization: Bearer {{authToken}}

###
POST https://fitapi.rudyah.com/users/{{userId}}/measurements
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "weight": 220,
    "unit": "imperial"
}

###
@measurementId=61b5affa0600492029c5f7e4

GET https://fitapi.rudyah.com/users/{userId}/measurements/{{measurementId}}
content-type: application/json
Authorization: Bearer {{authToken}}

###
PATCH https://fitapi.rudyah.com/users/61b58e60b32084150e3d5d58/measurements/{{measurementId}}
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "date": "2021-12-11T08:10:16.451Z"
}

###
DELETE https://fitapi.rudyah.com/users/61b58e60b32084150e3d5d58/measurements/{{measurementId}}
content-type: application/json
Authorization: Bearer {{authToken}}



# foods

###
GET https://fitapi.rudyah.com/users/{{userId}}/foods
Authorization: Bearer {{authToken}}

###
POST https://fitapi.rudyah.com/users/{{userId}}/foods
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "big mac",
    "calories": 500
}

###
POST https://fitapi.rudyah.com/users/{{userId}}/foods
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "slice of bread",
    "calories": 100
}


###
@foodId=61c6260da69dd547843d57d7

GET https://fitapi.rudyah.com/users/{{userId}}/foods/{{foodId}}
content-type: application/json
Authorization: Bearer {{authToken}}

###
PATCH https://fitapi.rudyah.com/users/{{userId}}/foods/{{foodId}}
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "date": "2021-12-24T19:57:01.444Z"
}

###
DELETE https://fitapi.rudyah.com/users/{{userId}}/foods/{{foodId}}
content-type: application/json
Authorization: Bearer {{authToken}}


###
GET https://fitapi.rudyah.com/users/{{userId}}/foods?name=c
Authorization: Bearer {{authToken}}