
GET https://fitapi.rudyah.com/users

###

POST http://localhost:3838/register
Content-Type: application/x-www-form-urlencoded

username=frankie
&password=bvtca3
&passwordConfirm=bvtca3
&gender=male
&height=65
&birthDate=01/01/1990

###

POST http://localhost:3838/login HTTP/2.0
Content-Type: application/x-www-form-urlencoded

username=frankie
&password=bvtca3

###
@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYjU4ZTYwYjMyMDg0MTUwZTNkNWQ1OCIsImlhdCI6MTY0MDEwMDk5NSwiZXhwIjoxNjQwMTg3Mzk1fQ.gBELeRhMx1TQnf2HkFOmvXq5ZeZVBqSuFVyeXW45bQM
@userId=61b58e60b32084150e3d5d58

###
GET http://localhost:3838/users/{{userId}}/settings
Authorization: Bearer {{authToken}}


# measurements

###
GET http://localhost:3838/users/{{userId}}/measurements
Authorization: Bearer {{authToken}}

###
POST http://localhost:3838/users/{{userId}}/measurements
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "weight": 210,
    "unit": "imperial",
    "strategy": "cut"
}

###
@measurementId=61b5affa0600492029c5f7e4

GET http://localhost:3838/users/61b58e60b32084150e3d5d58/measurements/{{measurementId}}
content-type: application/json
Authorization: Bearer {{authToken}}

###
PATCH http://localhost:3838/users/61b58e60b32084150e3d5d58/measurements/{{measurementId}}
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "date": "2021-12-11T08:10:16.451Z"
}

###
DELETE http://localhost:3838/users/61b58e60b32084150e3d5d58/measurements/{{measurementId}}
content-type: application/json
Authorization: Bearer {{authToken}}



# foods

###
GET http://localhost:3838/users/61b58e60b32084150e3d5d58/foods
Authorization: Bearer {{authToken}}

###
POST http://localhost:3838/users/61b58e60b32084150e3d5d58/foods
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "candy",
    "calories": 80
}

###
DELETE http://localhost:3838/users/61b58e60b32084150e3d5d58/foods
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "foods": ["61bf037403e88c187fe34cf6", "61b5c80995380d31413b2b95"]
}

###
@foodId=61b5b5c8c548c827aecbec4e

GET http://localhost:3838/users/61b58e60b32084150e3d5d58/foods/{{foodId}}
content-type: application/json
Authorization: Bearer {{authToken}}

###
PATCH http://localhost:3838/users/61b58e60b32084150e3d5d58/foods/{{foodId}}
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "date": "2021-12-21T08:41:44.976Z"
}

###
DELETE http://localhost:3838/users/61b58e60b32084150e3d5d58/foods/{{foodId}}
content-type: application/json
Authorization: Bearer {{authToken}}


###
GET http://localhost:3838/users/61b58e60b32084150e3d5d58/foods?name=ree
Authorization: Bearer {{authToken}}